//
//  PostgresKeywords.swift
//  PostgresGUI
//
//  Comprehensive PostgreSQL keyword catalog for SQL autocomplete.
//

import Foundation

enum PostgresKeywordCategory: String, Sendable {
    case reserved = "reserved"
    case unreserved = "unreserved"
    case reservedFuncType = "reserved (can be function or type name)"
    case unreservedNoFuncType = "unreserved (cannot be function or type name)"

    var shortLabel: String {
        switch self {
        case .reserved:
            return "keyword (reserved)"
        case .unreserved:
            return "keyword"
        case .reservedFuncType:
            return "keyword (reserved)"
        case .unreservedNoFuncType:
            return "keyword"
        }
    }
}

struct PostgresKeyword: Sendable {
    let word: String
    let category: PostgresKeywordCategory
}

enum PostgresKeywords {
    /// All PostgreSQL keywords from the official keyword catalog.
    /// Source: PostgreSQL documentation, `pg_get_keywords()`.
    static let all: [PostgresKeyword] = [
        // --- Reserved (R) ---
        PostgresKeyword(word: "ALL", category: .reserved),
        PostgresKeyword(word: "ANALYSE", category: .reserved),
        PostgresKeyword(word: "ANALYZE", category: .reserved),
        PostgresKeyword(word: "AND", category: .reserved),
        PostgresKeyword(word: "ANY", category: .reserved),
        PostgresKeyword(word: "ARRAY", category: .reserved),
        PostgresKeyword(word: "AS", category: .reserved),
        PostgresKeyword(word: "ASC", category: .reserved),
        PostgresKeyword(word: "ASYMMETRIC", category: .reserved),
        PostgresKeyword(word: "BOTH", category: .reserved),
        PostgresKeyword(word: "CASE", category: .reserved),
        PostgresKeyword(word: "CAST", category: .reserved),
        PostgresKeyword(word: "CHECK", category: .reserved),
        PostgresKeyword(word: "COLLATE", category: .reserved),
        PostgresKeyword(word: "COLUMN", category: .reserved),
        PostgresKeyword(word: "CONSTRAINT", category: .reserved),
        PostgresKeyword(word: "CREATE", category: .reserved),
        PostgresKeyword(word: "CURRENT_CATALOG", category: .reserved),
        PostgresKeyword(word: "CURRENT_DATE", category: .reserved),
        PostgresKeyword(word: "CURRENT_ROLE", category: .reserved),
        PostgresKeyword(word: "CURRENT_TIME", category: .reserved),
        PostgresKeyword(word: "CURRENT_TIMESTAMP", category: .reserved),
        PostgresKeyword(word: "CURRENT_USER", category: .reserved),
        PostgresKeyword(word: "DEFAULT", category: .reserved),
        PostgresKeyword(word: "DEFERRABLE", category: .reserved),
        PostgresKeyword(word: "DESC", category: .reserved),
        PostgresKeyword(word: "DISTINCT", category: .reserved),
        PostgresKeyword(word: "DO", category: .reserved),
        PostgresKeyword(word: "ELSE", category: .reserved),
        PostgresKeyword(word: "END", category: .reserved),
        PostgresKeyword(word: "EXCEPT", category: .reserved),
        PostgresKeyword(word: "FALSE", category: .reserved),
        PostgresKeyword(word: "FETCH", category: .reserved),
        PostgresKeyword(word: "FOR", category: .reserved),
        PostgresKeyword(word: "FOREIGN", category: .reserved),
        PostgresKeyword(word: "FROM", category: .reserved),
        PostgresKeyword(word: "GRANT", category: .reserved),
        PostgresKeyword(word: "GROUP", category: .reserved),
        PostgresKeyword(word: "HAVING", category: .reserved),
        PostgresKeyword(word: "IN", category: .reserved),
        PostgresKeyword(word: "INITIALLY", category: .reserved),
        PostgresKeyword(word: "INTERSECT", category: .reserved),
        PostgresKeyword(word: "INTO", category: .reserved),
        PostgresKeyword(word: "LATERAL", category: .reserved),
        PostgresKeyword(word: "LEADING", category: .reserved),
        PostgresKeyword(word: "LIMIT", category: .reserved),
        PostgresKeyword(word: "LOCALTIME", category: .reserved),
        PostgresKeyword(word: "LOCALTIMESTAMP", category: .reserved),
        PostgresKeyword(word: "NOT", category: .reserved),
        PostgresKeyword(word: "NULL", category: .reserved),
        PostgresKeyword(word: "OFFSET", category: .reserved),
        PostgresKeyword(word: "ON", category: .reserved),
        PostgresKeyword(word: "ONLY", category: .reserved),
        PostgresKeyword(word: "OR", category: .reserved),
        PostgresKeyword(word: "ORDER", category: .reserved),
        PostgresKeyword(word: "PLACING", category: .reserved),
        PostgresKeyword(word: "PRIMARY", category: .reserved),
        PostgresKeyword(word: "REFERENCES", category: .reserved),
        PostgresKeyword(word: "RETURNING", category: .reserved),
        PostgresKeyword(word: "SELECT", category: .reserved),
        PostgresKeyword(word: "SESSION_USER", category: .reserved),
        PostgresKeyword(word: "SOME", category: .reserved),
        PostgresKeyword(word: "SYMMETRIC", category: .reserved),
        PostgresKeyword(word: "TABLE", category: .reserved),
        PostgresKeyword(word: "THEN", category: .reserved),
        PostgresKeyword(word: "TO", category: .reserved),
        PostgresKeyword(word: "TRAILING", category: .reserved),
        PostgresKeyword(word: "TRUE", category: .reserved),
        PostgresKeyword(word: "UNION", category: .reserved),
        PostgresKeyword(word: "UNIQUE", category: .reserved),
        PostgresKeyword(word: "USER", category: .reserved),
        PostgresKeyword(word: "USING", category: .reserved),
        PostgresKeyword(word: "VARIADIC", category: .reserved),
        PostgresKeyword(word: "WHEN", category: .reserved),
        PostgresKeyword(word: "WHERE", category: .reserved),
        PostgresKeyword(word: "WINDOW", category: .reserved),
        PostgresKeyword(word: "WITH", category: .reserved),

        // --- Reserved, can be function or type name (T) ---
        PostgresKeyword(word: "AUTHORIZATION", category: .reservedFuncType),
        PostgresKeyword(word: "BINARY", category: .reservedFuncType),
        PostgresKeyword(word: "COLLATION", category: .reservedFuncType),
        PostgresKeyword(word: "CONCURRENTLY", category: .reservedFuncType),
        PostgresKeyword(word: "CROSS", category: .reservedFuncType),
        PostgresKeyword(word: "CURRENT_SCHEMA", category: .reservedFuncType),
        PostgresKeyword(word: "FREEZE", category: .reservedFuncType),
        PostgresKeyword(word: "FULL", category: .reservedFuncType),
        PostgresKeyword(word: "ILIKE", category: .reservedFuncType),
        PostgresKeyword(word: "INNER", category: .reservedFuncType),
        PostgresKeyword(word: "IS", category: .reservedFuncType),
        PostgresKeyword(word: "ISNULL", category: .reservedFuncType),
        PostgresKeyword(word: "JOIN", category: .reservedFuncType),
        PostgresKeyword(word: "LEFT", category: .reservedFuncType),
        PostgresKeyword(word: "LIKE", category: .reservedFuncType),
        PostgresKeyword(word: "NATURAL", category: .reservedFuncType),
        PostgresKeyword(word: "NOTNULL", category: .reservedFuncType),
        PostgresKeyword(word: "OUTER", category: .reservedFuncType),
        PostgresKeyword(word: "OVERLAPS", category: .reservedFuncType),
        PostgresKeyword(word: "RIGHT", category: .reservedFuncType),
        PostgresKeyword(word: "SIMILAR", category: .reservedFuncType),
        PostgresKeyword(word: "TABLESAMPLE", category: .reservedFuncType),
        PostgresKeyword(word: "VERBOSE", category: .reservedFuncType),

        // --- Unreserved, cannot be function or type name (C) ---
        PostgresKeyword(word: "BETWEEN", category: .unreservedNoFuncType),
        PostgresKeyword(word: "BIGINT", category: .unreservedNoFuncType),
        PostgresKeyword(word: "BIT", category: .unreservedNoFuncType),
        PostgresKeyword(word: "BOOLEAN", category: .unreservedNoFuncType),
        PostgresKeyword(word: "CHAR", category: .unreservedNoFuncType),
        PostgresKeyword(word: "CHARACTER", category: .unreservedNoFuncType),
        PostgresKeyword(word: "COALESCE", category: .unreservedNoFuncType),
        PostgresKeyword(word: "DEC", category: .unreservedNoFuncType),
        PostgresKeyword(word: "DECIMAL", category: .unreservedNoFuncType),
        PostgresKeyword(word: "EXISTS", category: .unreservedNoFuncType),
        PostgresKeyword(word: "EXTRACT", category: .unreservedNoFuncType),
        PostgresKeyword(word: "FLOAT", category: .unreservedNoFuncType),
        PostgresKeyword(word: "GREATEST", category: .unreservedNoFuncType),
        PostgresKeyword(word: "GROUPING", category: .unreservedNoFuncType),
        PostgresKeyword(word: "INOUT", category: .unreservedNoFuncType),
        PostgresKeyword(word: "INT", category: .unreservedNoFuncType),
        PostgresKeyword(word: "INTEGER", category: .unreservedNoFuncType),
        PostgresKeyword(word: "INTERVAL", category: .unreservedNoFuncType),
        PostgresKeyword(word: "LEAST", category: .unreservedNoFuncType),
        PostgresKeyword(word: "NATIONAL", category: .unreservedNoFuncType),
        PostgresKeyword(word: "NCHAR", category: .unreservedNoFuncType),
        PostgresKeyword(word: "NONE", category: .unreservedNoFuncType),
        PostgresKeyword(word: "NORMALIZE", category: .unreservedNoFuncType),
        PostgresKeyword(word: "NULLIF", category: .unreservedNoFuncType),
        PostgresKeyword(word: "NUMERIC", category: .unreservedNoFuncType),
        PostgresKeyword(word: "OUT", category: .unreservedNoFuncType),
        PostgresKeyword(word: "OVERLAY", category: .unreservedNoFuncType),
        PostgresKeyword(word: "POSITION", category: .unreservedNoFuncType),
        PostgresKeyword(word: "PRECISION", category: .unreservedNoFuncType),
        PostgresKeyword(word: "REAL", category: .unreservedNoFuncType),
        PostgresKeyword(word: "ROW", category: .unreservedNoFuncType),
        PostgresKeyword(word: "SETOF", category: .unreservedNoFuncType),
        PostgresKeyword(word: "SMALLINT", category: .unreservedNoFuncType),
        PostgresKeyword(word: "SUBSTRING", category: .unreservedNoFuncType),
        PostgresKeyword(word: "TIME", category: .unreservedNoFuncType),
        PostgresKeyword(word: "TIMESTAMP", category: .unreservedNoFuncType),
        PostgresKeyword(word: "TREAT", category: .unreservedNoFuncType),
        PostgresKeyword(word: "TRIM", category: .unreservedNoFuncType),
        PostgresKeyword(word: "VALUES", category: .unreservedNoFuncType),
        PostgresKeyword(word: "VARCHAR", category: .unreservedNoFuncType),
        PostgresKeyword(word: "XMLATTRIBUTES", category: .unreservedNoFuncType),
        PostgresKeyword(word: "XMLCONCAT", category: .unreservedNoFuncType),
        PostgresKeyword(word: "XMLELEMENT", category: .unreservedNoFuncType),
        PostgresKeyword(word: "XMLEXISTS", category: .unreservedNoFuncType),
        PostgresKeyword(word: "XMLFOREST", category: .unreservedNoFuncType),
        PostgresKeyword(word: "XMLNAMESPACES", category: .unreservedNoFuncType),
        PostgresKeyword(word: "XMLPARSE", category: .unreservedNoFuncType),
        PostgresKeyword(word: "XMLPI", category: .unreservedNoFuncType),
        PostgresKeyword(word: "XMLROOT", category: .unreservedNoFuncType),
        PostgresKeyword(word: "XMLSERIALIZE", category: .unreservedNoFuncType),
        PostgresKeyword(word: "XMLTABLE", category: .unreservedNoFuncType),

        // --- Unreserved (U) ---
        PostgresKeyword(word: "ABORT", category: .unreserved),
        PostgresKeyword(word: "ABSOLUTE", category: .unreserved),
        PostgresKeyword(word: "ACCESS", category: .unreserved),
        PostgresKeyword(word: "ACTION", category: .unreserved),
        PostgresKeyword(word: "ADD", category: .unreserved),
        PostgresKeyword(word: "ADMIN", category: .unreserved),
        PostgresKeyword(word: "AFTER", category: .unreserved),
        PostgresKeyword(word: "AGGREGATE", category: .unreserved),
        PostgresKeyword(word: "ALSO", category: .unreserved),
        PostgresKeyword(word: "ALTER", category: .unreserved),
        PostgresKeyword(word: "ALWAYS", category: .unreserved),
        PostgresKeyword(word: "ASENSITIVE", category: .unreserved),
        PostgresKeyword(word: "ASSERTION", category: .unreserved),
        PostgresKeyword(word: "ASSIGNMENT", category: .unreserved),
        PostgresKeyword(word: "AT", category: .unreserved),
        PostgresKeyword(word: "ATOMIC", category: .unreserved),
        PostgresKeyword(word: "ATTACH", category: .unreserved),
        PostgresKeyword(word: "ATTRIBUTE", category: .unreserved),
        PostgresKeyword(word: "BACKWARD", category: .unreserved),
        PostgresKeyword(word: "BEFORE", category: .unreserved),
        PostgresKeyword(word: "BEGIN", category: .unreserved),
        PostgresKeyword(word: "BREADTH", category: .unreserved),
        PostgresKeyword(word: "BY", category: .unreserved),
        PostgresKeyword(word: "CACHE", category: .unreserved),
        PostgresKeyword(word: "CALL", category: .unreserved),
        PostgresKeyword(word: "CALLED", category: .unreserved),
        PostgresKeyword(word: "CASCADE", category: .unreserved),
        PostgresKeyword(word: "CASCADED", category: .unreserved),
        PostgresKeyword(word: "CATALOG", category: .unreserved),
        PostgresKeyword(word: "CHAIN", category: .unreserved),
        PostgresKeyword(word: "CHARACTERISTICS", category: .unreserved),
        PostgresKeyword(word: "CHECKPOINT", category: .unreserved),
        PostgresKeyword(word: "CLASS", category: .unreserved),
        PostgresKeyword(word: "CLOSE", category: .unreserved),
        PostgresKeyword(word: "CLUSTER", category: .unreserved),
        PostgresKeyword(word: "COLUMNS", category: .unreserved),
        PostgresKeyword(word: "COMMENT", category: .unreserved),
        PostgresKeyword(word: "COMMENTS", category: .unreserved),
        PostgresKeyword(word: "COMMIT", category: .unreserved),
        PostgresKeyword(word: "COMMITTED", category: .unreserved),
        PostgresKeyword(word: "COMPRESSION", category: .unreserved),
        PostgresKeyword(word: "CONFIGURATION", category: .unreserved),
        PostgresKeyword(word: "CONFLICT", category: .unreserved),
        PostgresKeyword(word: "CONNECTION", category: .unreserved),
        PostgresKeyword(word: "CONSTRAINTS", category: .unreserved),
        PostgresKeyword(word: "CONTENT", category: .unreserved),
        PostgresKeyword(word: "CONTINUE", category: .unreserved),
        PostgresKeyword(word: "CONVERSION", category: .unreserved),
        PostgresKeyword(word: "COPY", category: .unreserved),
        PostgresKeyword(word: "COST", category: .unreserved),
        PostgresKeyword(word: "CSV", category: .unreserved),
        PostgresKeyword(word: "CUBE", category: .unreserved),
        PostgresKeyword(word: "CURRENT", category: .unreserved),
        PostgresKeyword(word: "CURSOR", category: .unreserved),
        PostgresKeyword(word: "CYCLE", category: .unreserved),
        PostgresKeyword(word: "DATA", category: .unreserved),
        PostgresKeyword(word: "DATABASE", category: .unreserved),
        PostgresKeyword(word: "DAY", category: .unreserved),
        PostgresKeyword(word: "DEALLOCATE", category: .unreserved),
        PostgresKeyword(word: "DECLARE", category: .unreserved),
        PostgresKeyword(word: "DEFAULTS", category: .unreserved),
        PostgresKeyword(word: "DEFERRED", category: .unreserved),
        PostgresKeyword(word: "DEFINER", category: .unreserved),
        PostgresKeyword(word: "DELETE", category: .unreserved),
        PostgresKeyword(word: "DELIMITER", category: .unreserved),
        PostgresKeyword(word: "DELIMITERS", category: .unreserved),
        PostgresKeyword(word: "DEPENDS", category: .unreserved),
        PostgresKeyword(word: "DEPTH", category: .unreserved),
        PostgresKeyword(word: "DETACH", category: .unreserved),
        PostgresKeyword(word: "DICTIONARY", category: .unreserved),
        PostgresKeyword(word: "DISABLE", category: .unreserved),
        PostgresKeyword(word: "DISCARD", category: .unreserved),
        PostgresKeyword(word: "DOCUMENT", category: .unreserved),
        PostgresKeyword(word: "DOMAIN", category: .unreserved),
        PostgresKeyword(word: "DOUBLE", category: .unreserved),
        PostgresKeyword(word: "DROP", category: .unreserved),
        PostgresKeyword(word: "EACH", category: .unreserved),
        PostgresKeyword(word: "ENABLE", category: .unreserved),
        PostgresKeyword(word: "ENCODING", category: .unreserved),
        PostgresKeyword(word: "ENCRYPTED", category: .unreserved),
        PostgresKeyword(word: "ENUM", category: .unreserved),
        PostgresKeyword(word: "ESCAPE", category: .unreserved),
        PostgresKeyword(word: "EVENT", category: .unreserved),
        PostgresKeyword(word: "EXCLUDE", category: .unreserved),
        PostgresKeyword(word: "EXCLUDING", category: .unreserved),
        PostgresKeyword(word: "EXCLUSIVE", category: .unreserved),
        PostgresKeyword(word: "EXECUTE", category: .unreserved),
        PostgresKeyword(word: "EXPLAIN", category: .unreserved),
        PostgresKeyword(word: "EXPRESSION", category: .unreserved),
        PostgresKeyword(word: "EXTENSION", category: .unreserved),
        PostgresKeyword(word: "EXTERNAL", category: .unreserved),
        PostgresKeyword(word: "FAMILY", category: .unreserved),
        PostgresKeyword(word: "FILTER", category: .unreserved),
        PostgresKeyword(word: "FINALIZE", category: .unreserved),
        PostgresKeyword(word: "FIRST", category: .unreserved),
        PostgresKeyword(word: "FOLLOWING", category: .unreserved),
        PostgresKeyword(word: "FORCE", category: .unreserved),
        PostgresKeyword(word: "FORWARD", category: .unreserved),
        PostgresKeyword(word: "FUNCTION", category: .unreserved),
        PostgresKeyword(word: "FUNCTIONS", category: .unreserved),
        PostgresKeyword(word: "GENERATED", category: .unreserved),
        PostgresKeyword(word: "GLOBAL", category: .unreserved),
        PostgresKeyword(word: "GRANTED", category: .unreserved),
        PostgresKeyword(word: "GROUPS", category: .unreserved),
        PostgresKeyword(word: "HANDLER", category: .unreserved),
        PostgresKeyword(word: "HEADER", category: .unreserved),
        PostgresKeyword(word: "HOLD", category: .unreserved),
        PostgresKeyword(word: "HOUR", category: .unreserved),
        PostgresKeyword(word: "IDENTITY", category: .unreserved),
        PostgresKeyword(word: "IF", category: .unreserved),
        PostgresKeyword(word: "IMMEDIATE", category: .unreserved),
        PostgresKeyword(word: "IMMUTABLE", category: .unreserved),
        PostgresKeyword(word: "IMPLICIT", category: .unreserved),
        PostgresKeyword(word: "IMPORT", category: .unreserved),
        PostgresKeyword(word: "INCLUDE", category: .unreserved),
        PostgresKeyword(word: "INCLUDING", category: .unreserved),
        PostgresKeyword(word: "INCREMENT", category: .unreserved),
        PostgresKeyword(word: "INDEX", category: .unreserved),
        PostgresKeyword(word: "INDEXES", category: .unreserved),
        PostgresKeyword(word: "INHERIT", category: .unreserved),
        PostgresKeyword(word: "INHERITS", category: .unreserved),
        PostgresKeyword(word: "INLINE", category: .unreserved),
        PostgresKeyword(word: "INPUT", category: .unreserved),
        PostgresKeyword(word: "INSENSITIVE", category: .unreserved),
        PostgresKeyword(word: "INSERT", category: .unreserved),
        PostgresKeyword(word: "INSTEAD", category: .unreserved),
        PostgresKeyword(word: "INVOKER", category: .unreserved),
        PostgresKeyword(word: "ISOLATION", category: .unreserved),
        PostgresKeyword(word: "KEY", category: .unreserved),
        PostgresKeyword(word: "LABEL", category: .unreserved),
        PostgresKeyword(word: "LANGUAGE", category: .unreserved),
        PostgresKeyword(word: "LARGE", category: .unreserved),
        PostgresKeyword(word: "LAST", category: .unreserved),
        PostgresKeyword(word: "LEAKPROOF", category: .unreserved),
        PostgresKeyword(word: "LEVEL", category: .unreserved),
        PostgresKeyword(word: "LISTEN", category: .unreserved),
        PostgresKeyword(word: "LOAD", category: .unreserved),
        PostgresKeyword(word: "LOCAL", category: .unreserved),
        PostgresKeyword(word: "LOCATION", category: .unreserved),
        PostgresKeyword(word: "LOCK", category: .unreserved),
        PostgresKeyword(word: "LOCKED", category: .unreserved),
        PostgresKeyword(word: "LOGGED", category: .unreserved),
        PostgresKeyword(word: "MAPPING", category: .unreserved),
        PostgresKeyword(word: "MATCH", category: .unreserved),
        PostgresKeyword(word: "MATCHED", category: .unreserved),
        PostgresKeyword(word: "MATERIALIZED", category: .unreserved),
        PostgresKeyword(word: "MAXVALUE", category: .unreserved),
        PostgresKeyword(word: "MERGE", category: .unreserved),
        PostgresKeyword(word: "METHOD", category: .unreserved),
        PostgresKeyword(word: "MINUTE", category: .unreserved),
        PostgresKeyword(word: "MINVALUE", category: .unreserved),
        PostgresKeyword(word: "MODE", category: .unreserved),
        PostgresKeyword(word: "MONTH", category: .unreserved),
        PostgresKeyword(word: "MOVE", category: .unreserved),
        PostgresKeyword(word: "NAME", category: .unreserved),
        PostgresKeyword(word: "NAMES", category: .unreserved),
        PostgresKeyword(word: "NEW", category: .unreserved),
        PostgresKeyword(word: "NEXT", category: .unreserved),
        PostgresKeyword(word: "NFC", category: .unreserved),
        PostgresKeyword(word: "NFD", category: .unreserved),
        PostgresKeyword(word: "NFKC", category: .unreserved),
        PostgresKeyword(word: "NFKD", category: .unreserved),
        PostgresKeyword(word: "NO", category: .unreserved),
        PostgresKeyword(word: "NORMALIZED", category: .unreserved),
        PostgresKeyword(word: "NOTHING", category: .unreserved),
        PostgresKeyword(word: "NOTIFY", category: .unreserved),
        PostgresKeyword(word: "NOWAIT", category: .unreserved),
        PostgresKeyword(word: "NULLS", category: .unreserved),
        PostgresKeyword(word: "OBJECT", category: .unreserved),
        PostgresKeyword(word: "OF", category: .unreserved),
        PostgresKeyword(word: "OFF", category: .unreserved),
        PostgresKeyword(word: "OIDS", category: .unreserved),
        PostgresKeyword(word: "OLD", category: .unreserved),
        PostgresKeyword(word: "OPERATOR", category: .unreserved),
        PostgresKeyword(word: "OPTION", category: .unreserved),
        PostgresKeyword(word: "OPTIONS", category: .unreserved),
        PostgresKeyword(word: "ORDINALITY", category: .unreserved),
        PostgresKeyword(word: "OTHERS", category: .unreserved),
        PostgresKeyword(word: "OVER", category: .unreserved),
        PostgresKeyword(word: "OVERRIDING", category: .unreserved),
        PostgresKeyword(word: "OWNED", category: .unreserved),
        PostgresKeyword(word: "OWNER", category: .unreserved),
        PostgresKeyword(word: "PARALLEL", category: .unreserved),
        PostgresKeyword(word: "PARAMETER", category: .unreserved),
        PostgresKeyword(word: "PARSER", category: .unreserved),
        PostgresKeyword(word: "PARTIAL", category: .unreserved),
        PostgresKeyword(word: "PARTITION", category: .unreserved),
        PostgresKeyword(word: "PASSING", category: .unreserved),
        PostgresKeyword(word: "PASSWORD", category: .unreserved),
        PostgresKeyword(word: "PLANS", category: .unreserved),
        PostgresKeyword(word: "POLICY", category: .unreserved),
        PostgresKeyword(word: "PRECEDING", category: .unreserved),
        PostgresKeyword(word: "PREPARE", category: .unreserved),
        PostgresKeyword(word: "PREPARED", category: .unreserved),
        PostgresKeyword(word: "PRESERVE", category: .unreserved),
        PostgresKeyword(word: "PRIOR", category: .unreserved),
        PostgresKeyword(word: "PRIVILEGES", category: .unreserved),
        PostgresKeyword(word: "PROCEDURAL", category: .unreserved),
        PostgresKeyword(word: "PROCEDURE", category: .unreserved),
        PostgresKeyword(word: "PROCEDURES", category: .unreserved),
        PostgresKeyword(word: "PROGRAM", category: .unreserved),
        PostgresKeyword(word: "PUBLICATION", category: .unreserved),
        PostgresKeyword(word: "QUOTE", category: .unreserved),
        PostgresKeyword(word: "RANGE", category: .unreserved),
        PostgresKeyword(word: "READ", category: .unreserved),
        PostgresKeyword(word: "REASSIGN", category: .unreserved),
        PostgresKeyword(word: "RECHECK", category: .unreserved),
        PostgresKeyword(word: "RECURSIVE", category: .unreserved),
        PostgresKeyword(word: "REF", category: .unreserved),
        PostgresKeyword(word: "REFERENCING", category: .unreserved),
        PostgresKeyword(word: "REFRESH", category: .unreserved),
        PostgresKeyword(word: "REINDEX", category: .unreserved),
        PostgresKeyword(word: "RELATIVE", category: .unreserved),
        PostgresKeyword(word: "RELEASE", category: .unreserved),
        PostgresKeyword(word: "RENAME", category: .unreserved),
        PostgresKeyword(word: "REPEATABLE", category: .unreserved),
        PostgresKeyword(word: "REPLACE", category: .unreserved),
        PostgresKeyword(word: "REPLICA", category: .unreserved),
        PostgresKeyword(word: "RESET", category: .unreserved),
        PostgresKeyword(word: "RESTART", category: .unreserved),
        PostgresKeyword(word: "RESTRICT", category: .unreserved),
        PostgresKeyword(word: "RETURN", category: .unreserved),
        PostgresKeyword(word: "RETURNS", category: .unreserved),
        PostgresKeyword(word: "REVOKE", category: .unreserved),
        PostgresKeyword(word: "ROLE", category: .unreserved),
        PostgresKeyword(word: "ROLLBACK", category: .unreserved),
        PostgresKeyword(word: "ROLLUP", category: .unreserved),
        PostgresKeyword(word: "ROUTINE", category: .unreserved),
        PostgresKeyword(word: "ROUTINES", category: .unreserved),
        PostgresKeyword(word: "ROWS", category: .unreserved),
        PostgresKeyword(word: "RULE", category: .unreserved),
        PostgresKeyword(word: "SAVEPOINT", category: .unreserved),
        PostgresKeyword(word: "SCHEMA", category: .unreserved),
        PostgresKeyword(word: "SCHEMAS", category: .unreserved),
        PostgresKeyword(word: "SCROLL", category: .unreserved),
        PostgresKeyword(word: "SEARCH", category: .unreserved),
        PostgresKeyword(word: "SECOND", category: .unreserved),
        PostgresKeyword(word: "SECURITY", category: .unreserved),
        PostgresKeyword(word: "SEQUENCE", category: .unreserved),
        PostgresKeyword(word: "SEQUENCES", category: .unreserved),
        PostgresKeyword(word: "SERIALIZABLE", category: .unreserved),
        PostgresKeyword(word: "SERVER", category: .unreserved),
        PostgresKeyword(word: "SESSION", category: .unreserved),
        PostgresKeyword(word: "SET", category: .unreserved),
        PostgresKeyword(word: "SETS", category: .unreserved),
        PostgresKeyword(word: "SHARE", category: .unreserved),
        PostgresKeyword(word: "SHOW", category: .unreserved),
        PostgresKeyword(word: "SIMPLE", category: .unreserved),
        PostgresKeyword(word: "SKIP", category: .unreserved),
        PostgresKeyword(word: "SNAPSHOT", category: .unreserved),
        PostgresKeyword(word: "SQL", category: .unreserved),
        PostgresKeyword(word: "STABLE", category: .unreserved),
        PostgresKeyword(word: "STANDALONE", category: .unreserved),
        PostgresKeyword(word: "START", category: .unreserved),
        PostgresKeyword(word: "STATEMENT", category: .unreserved),
        PostgresKeyword(word: "STATISTICS", category: .unreserved),
        PostgresKeyword(word: "STDIN", category: .unreserved),
        PostgresKeyword(word: "STDOUT", category: .unreserved),
        PostgresKeyword(word: "STORAGE", category: .unreserved),
        PostgresKeyword(word: "STORED", category: .unreserved),
        PostgresKeyword(word: "STRICT", category: .unreserved),
        PostgresKeyword(word: "STRIP", category: .unreserved),
        PostgresKeyword(word: "SUBSCRIPTION", category: .unreserved),
        PostgresKeyword(word: "SUPPORT", category: .unreserved),
        PostgresKeyword(word: "SYSID", category: .unreserved),
        PostgresKeyword(word: "SYSTEM", category: .unreserved),
        PostgresKeyword(word: "TABLES", category: .unreserved),
        PostgresKeyword(word: "TABLESPACE", category: .unreserved),
        PostgresKeyword(word: "TEMP", category: .unreserved),
        PostgresKeyword(word: "TEMPLATE", category: .unreserved),
        PostgresKeyword(word: "TEMPORARY", category: .unreserved),
        PostgresKeyword(word: "TEXT", category: .unreserved),
        PostgresKeyword(word: "TIES", category: .unreserved),
        PostgresKeyword(word: "TRANSACTION", category: .unreserved),
        PostgresKeyword(word: "TRANSFORM", category: .unreserved),
        PostgresKeyword(word: "TRIGGER", category: .unreserved),
        PostgresKeyword(word: "TRUNCATE", category: .unreserved),
        PostgresKeyword(word: "TRUSTED", category: .unreserved),
        PostgresKeyword(word: "TYPE", category: .unreserved),
        PostgresKeyword(word: "TYPES", category: .unreserved),
        PostgresKeyword(word: "UESCAPE", category: .unreserved),
        PostgresKeyword(word: "UNBOUNDED", category: .unreserved),
        PostgresKeyword(word: "UNCOMMITTED", category: .unreserved),
        PostgresKeyword(word: "UNENCRYPTED", category: .unreserved),
        PostgresKeyword(word: "UNKNOWN", category: .unreserved),
        PostgresKeyword(word: "UNLISTEN", category: .unreserved),
        PostgresKeyword(word: "UNLOGGED", category: .unreserved),
        PostgresKeyword(word: "UNTIL", category: .unreserved),
        PostgresKeyword(word: "UPDATE", category: .unreserved),
        PostgresKeyword(word: "VACUUM", category: .unreserved),
        PostgresKeyword(word: "VALID", category: .unreserved),
        PostgresKeyword(word: "VALIDATE", category: .unreserved),
        PostgresKeyword(word: "VALIDATOR", category: .unreserved),
        PostgresKeyword(word: "VALUE", category: .unreserved),
        PostgresKeyword(word: "VARYING", category: .unreserved),
        PostgresKeyword(word: "VERSION", category: .unreserved),
        PostgresKeyword(word: "VIEW", category: .unreserved),
        PostgresKeyword(word: "VIEWS", category: .unreserved),
        PostgresKeyword(word: "VOLATILE", category: .unreserved),
        PostgresKeyword(word: "WHITESPACE", category: .unreserved),
        PostgresKeyword(word: "WITHIN", category: .unreserved),
        PostgresKeyword(word: "WITHOUT", category: .unreserved),
        PostgresKeyword(word: "WORK", category: .unreserved),
        PostgresKeyword(word: "WRAPPER", category: .unreserved),
        PostgresKeyword(word: "WRITE", category: .unreserved),
        PostgresKeyword(word: "XML", category: .unreserved),
        PostgresKeyword(word: "YEAR", category: .unreserved),
        PostgresKeyword(word: "YES", category: .unreserved),
        PostgresKeyword(word: "ZONE", category: .unreserved),
    ]

    /// Frequently-used SQL keywords prioritized in general keyword context.
    /// These appear first when user starts typing with no specific context.
    static let commonKeywords: [PostgresKeyword] = {
        let prioritized: Set<String> = [
            "SELECT", "FROM", "WHERE", "JOIN", "LEFT", "RIGHT", "INNER",
            "FULL", "CROSS", "OUTER", "NATURAL", "ON", "ORDER", "GROUP",
            "BY", "HAVING", "INSERT", "INTO", "VALUES", "UPDATE", "SET",
            "DELETE", "RETURNING", "LIMIT", "OFFSET", "WITH", "UNION",
            "EXCEPT", "INTERSECT", "EXISTS", "AND", "OR", "NOT", "NULL",
            "AS", "IN", "BETWEEN", "LIKE", "ILIKE", "IS", "CASE", "WHEN",
            "THEN", "ELSE", "END", "DISTINCT", "ALL", "ANY", "SOME",
            "TRUE", "FALSE", "CREATE", "ALTER", "DROP", "TABLE", "INDEX",
            "VIEW", "SCHEMA", "DATABASE", "FUNCTION", "TRIGGER",
            "SEQUENCE", "TYPE", "FOREIGN", "PRIMARY", "KEY", "REFERENCES",
            "CONSTRAINT", "UNIQUE", "CHECK", "DEFAULT", "CASCADE",
            "RESTRICT", "GRANT", "REVOKE", "BEGIN", "COMMIT", "ROLLBACK",
            "EXPLAIN", "ANALYZE", "COALESCE", "NULLIF", "CAST",
            "EXTRACT", "TRIM", "SUBSTRING", "INTEGER", "VARCHAR", "TEXT",
            "BOOLEAN", "TIMESTAMP", "BIGINT", "SMALLINT", "NUMERIC",
            "REAL", "FLOAT", "DECIMAL",
        ]
        return all.filter { prioritized.contains($0.word) }
    }()

    /// Multi-word compound keywords for common SQL idioms.
    static let compoundKeywords: [String] = [
        "LEFT JOIN",
        "RIGHT JOIN",
        "INNER JOIN",
        "FULL JOIN",
        "CROSS JOIN",
        "FULL OUTER JOIN",
        "LEFT OUTER JOIN",
        "RIGHT OUTER JOIN",
        "NATURAL JOIN",
        "ORDER BY",
        "GROUP BY",
        "INSERT INTO",
        "DELETE FROM",
        "NOT NULL",
        "IS NULL",
        "IS NOT NULL",
        "PRIMARY KEY",
        "FOREIGN KEY",
        "IF EXISTS",
        "IF NOT EXISTS",
        "CREATE TABLE",
        "CREATE INDEX",
        "CREATE VIEW",
        "CREATE OR REPLACE",
        "ALTER TABLE",
        "DROP TABLE",
        "DROP INDEX",
    ]

    /// Post-relation clause keywords (used after FROM table_name).
    static let postRelationKeywords: [String] = [
        "JOIN",
        "LEFT JOIN",
        "RIGHT JOIN",
        "INNER JOIN",
        "FULL JOIN",
        "CROSS JOIN",
        "ON",
        "WHERE",
        "GROUP BY",
        "ORDER BY",
        "HAVING",
        "LIMIT",
        "OFFSET",
    ]
}
